project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!**/spatial-transcriptomics/*"
  preview:
    port: 3333
    browser: true
    watch-inputs: true
    timeout: 600


website:
  title: "Research Reference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: https://github.com/pranavmishra90/research-reference
        text: GitHub
    search: true
  open-graph: true
  sidebar:
    style: "docked"
    contents: auto
  page-footer: "Created by Pranav Kumar Mishra || License CC-BY-SA" 
  reader-mode: false
  repo-url: https://github.com/pranavmishra90/research-reference
  repo-actions: [issue, edit]
  site-url: ref.drpranavmishra.com



format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    lang: en-US
    email-obfuscation: javascript
    code-fold: true
    code-line-numbers: true
    code-overflow: wrap
    # grid:
    #   sidebar-width: 300px
    #   body-width: 900px
    default-image-extension: svg
    embed-resources: true


execute:
  freeze: auto
  cache: true

bibliography: ./references.bib
csl: ./ama.csl

citation: true
google-scholar: true

