project:
  type: website

website:
  title: "Research Reference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    search: true
  open-graph: true
  sidebar:
    style: "docked"
    contents: auto
  page-footer: "Pranav Mishra || License CC-BY-SA" 
  reader-mode: true
  repo-url: https://github.com/pranavmishra90/research-reference
  repo-actions: [edit, issue]


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: en-US
    email-obfuscation: javascript




