---
title: "10% Formalin (4% Paraformaldehyde)"
date: last-modified
date-format: full
author:
  - name: Pranav Mishra
    url: https://drpranavmishra.com
    orcid: 0000-0001-5219-6269 
    affiliation: Rush University
    affiliation-url: https://rushu.rush.edu 
citation: true
google-scholar: true

nocite: |
  @rd_systems_protocol_nodate
---
## Overview

The term "Formalin" specifically refers to a saturated solution of Formaldehyde, which is 37% w/v or about 40% v/v. This is a rather high concentration of formaldehyde. A common dilution is a 1:10, which is referred to as *10% Formalin* or *4% Formaldehyde (aka 4% Paraformaldehyde)*. "Paraformaldehyde" technically refers to a polymerized form of formaldehyde which is stable at room temperature without the addition of methanol. Upon addition to an aqueous solution, it dissolves into formaldehyde by breaking the polymer chain.

### Uses
Fixing tissue

## Components
1. $diH_2O$
2. $HCl$ (Dilute)
3. $NaOH$  (1 N)
4. Paraformaldehyde powder (Sigma Aldrich Cat 158127-500G)
5. 1X Phosphate Buffered Saline
6. Sterile container


## Protocol: Preparation of 1 liter of 4% PFA (10% Formalin)
1. In a vented hood, add 800 mL of PBS to a beaker with a stir bar on a hot plate set to $60 ^\circ C$
2. Add 40g of PFA powder to the heated PBS solution
3. Spin until mostly disolved ^[Note: the solution will appear like milk]
4. Raise the pH, by adding 1N $NaOH$ dropwise using a transfer pipette, until the solution clears ^[Note: Takes $\le$ 2 mL of 1N $NaOH$ to turn the solution clear.]
5. Cool to room temperature
6. Add 1x PBS until the volume reaches 1L total


## Storage
- Ideally, this should be prepared fresh for each use
- $2-8 ^\circ C$: 1 month
- $-20 ^\circ C$: several months


## References

::: {#refs}
:::