---
title: "Recipe: Tris-Buffered Saline (TBS)"
date: last-modified
date-format: full
author:
  - name: Pranav Mishra
    url: https://drpranavmishra.com
    orcid: 0000-0001-5219-6269 
    affiliation: Rush University
    affiliation-url: https://rushu.rush.edu 
citation: true
google-scholar: true
---

## Overview

Tris (trishydroxymethylaminomethane) $(HOCH_2)_3CNH_2$ has an effective buffer range between 7.1 and 9.1 (pKa 8.07 at $25 ^\circ C$)

### Uses

Wash buffer in Western Blots

## Components

-   $diH_2O$
-   *Tris Base* (Ficher BP154-1)
    -   Alternate Trizma HCl 24.23g
-   $12 N\space HCl$
-   $HCl$

## Protocol

### Comparison of TBS concentrations at 1x

| Component | Abcam (mM) | Abcam (g) | Thermo (mM) | Thermo (g) |
|-----------|:----------:|:---------:|:-----------:|:----------:|
| Tris base |     20     |    2.4    |     20      |    2.4     |
| NaCl      |    150     |    8.8    |     150     |    8.8     |

### 10x stock solution

We will be preparing 1L of 10x TBS for a stock solution.

1.  Add 800 mL of $diH_2O$ to orange top container
2.  Dissolve 24 g of *Tris Base* and 88 g $NaCl$ into the container
    1.  Use a larger stir bar on a high speed - it will take a few minutes to dissolve completely
3.  Titrate the pH with $12 N\space HCl$ to 7.6
4.  Add $diH_2O$ to bring the total volume to 1 L

**10x concentrations:** - Tris 200 mM - $NaCl$ 1500 mM

### 1x TBS solution

using the 10x solution described above

1.  Add 100 mL of *10x TBS solution* to an orange top container
2.  Add 900 mL of $diH_2O$
3.  Adjust pH to 7.6 using $12 N\space HCl$ (currently have 2N stock in the lab, will require more acid being used to neutralize)

**1x concentrations:** - Tris 20 mM - $NaCl$ 150 mM

## Notes

Abcam and Thermo have protocols in agreement. Phosphosolutions proposes 2mM Tris, 14 mM NaCl. Our group has more experience using the Abcam protocol, which is why it is listed here. Note that there are multiple different approaches to the concentrations when making TBS.

We currently have 2N HCl stock in the lab, so it requires significantly more HCl added to neutralize the Tris Base.

## References

1.  Western blot buffers and stock solutions. Abcam. https://www.abcam.com/protocols/buffer-and-stock-solutions-for-western-blot#TBS-10x
2.  Western Blot Protocols and Recipes. ThermoFicher Scientific. https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-gel-electrophoresis-information/western-blot-protocols.html

------------------------------------------------------------------------

## Supplemental

### Key resources table

| **REAGENT or RESOURCE** | **SOURCE** | **IDENTIFIER** |
|-------------------------|------------|----------------|
| **Chemicals**           |            |                |
| Tris Base               | Ficher     | Cat# BP154-1   |
| NaCl                    | Ficher     | Cat# S640-10   |
| HCl                     | Lab stock  | Lab Stock      |
