---
title: "Tris-Glycine SDS Running Buffer"
date: last-modified
date-format: full
author:
  - name: Pranav Mishra
    url: https://drpranavmishra.com
    orcid: 0000-0001-5219-6269 
    affiliation: Rush University
    affiliation-url: https://rushu.rush.edu 
citation: true
google-scholar: true
---


## Overview
Tris-Gycine Transfer Buffer has a pH of 8.3. Protocol adapted from Abcam and ThermoFicher<sup>1, 2</sup>

### Uses
Running buffer for Western Blot

## Components
- *Tris Base*
- *Glycine*
- $HCl$
- $diH_2O$

## Protocol

### 10x Stock
1. Add 700 mL of $diH_2O$ to a beaker
2. Dissolve 29 g of Tris base, 144 g of Glycine, and 10 g of SDS
3. Adjust pH using $HCl$, as needed
4. Add $diH_2O$ until the total volume reaches 1 L of solution

**Concentration of 1x Tris-Glycine SDS**
25 mM *Tris base*, 190 mM *glycine*, 0.1% *SDS*

## Notes
<!-- Some specific observations or modifications made -->

## References
1. Transfer and staining of proteins in western blot. Abcam. https://www.abcam.com/protocols/transfer-and-staining-of-proteins-in-western-blot
2. Western Blot Protocols and Recipes. ThermoFicher Scientific. https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-gel-electrophoresis-information/western-blot-protocols.html


---

## Supplemental

### Key resources table

|   REAGENT or RESOURCE          	|   SOURCE  	|   IDENTIFIER      	|
|--------------------------------	|-----------	|-------------------	|
|   Chemicals                    	|           	|                   	|
|   Tris Base                    	|   Ficher  	|   Cat# BP154-1    	|
|   Glycine                      	|   Sigma   	|   Cat# G-7126     	|
|   SDS - Electrophoresis Grade  	|   Fisher  	|   Cat# BP166-500  	|
|   HCl                          	| Lab Stock 	| N/A               	|
