---
title: "Tris-Glycine Transfer Buffer"
date: 2023-04-22
date-format: full
author:
  - name:
      given: Pranav Kumar
      family: Mishra
    affiliations:
      - ref: rushsurg
      - ref: rushortho
    corresponding: true
    url: https://drpranavmishra.com
    email: pranav_k_mishra@rush.edu
    orcid: 0000-0001-5219-6269
citation: true
google-scholar: true
---


## Overview
Tris-Gycine Transfer Buffer has a pH of 8.3. Protocol adapted from Abcam<sup>1</sup>

### Uses
Transfer buffer used in Western Blots

## Components
- *Tris Base*
- *Glycine*
- $HCl$
- 100% *Methanol*
- $diH_2O$

## Protocol

### 10x Stock of Transfer Buffer
1. Add 700 mL of $diH_2O$ to a beaker
2. Dissolve 30.25 g of *Tris Base* and 142.63 g of *Glycine* in the water
3. Adjust pH with $HCl$ to 8.3
4. Add 300mL of $diH_2O$ (total vol 1000 mL)

### 1x Transfer Buffer
1. Add 700 mL of $diH_2O$ to a beaker
2. Add 100 mL of 10x Stock Transfer Buffer
3. Adjust pH with $HCl$ to 8.3
4. Add 200mL of *100% Methanol* (total vol 1000 mL)


**1x concentrations:**
- Tris 25 mM
- Glycine 190 mM

## Notes

Concentrations of Tris and Glycine differ from ThermoFicher's protocols<sup>2</sup>, which recommend a 12.5 mM of Tris and 96 mM Glycine.


| Component 	| Abcam (mM) 	| Thermo (mM) 	|
|-----------	|------------	|-------------	|
| Tris base 	| 25         	| 12.5        	|
| Glycine   	| 190        	| 96          	|

## References
1. Transfer and staining of proteins in western blot. Abcam. https://www.abcam.com/protocols/transfer-and-staining-of-proteins-in-western-blot
2. Western Blot Protocols and Recipes. ThermoFicher Scientific. https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-gel-electrophoresis-information/western-blot-protocols.html



---

## Supplemental

### Key resources table

| REAGENT OR RESOURCE | SOURCE    | IDENTIFIER   |
|---------------------|-----------|--------------|
| **Chemicals**       |           |              |
| Tris Base           | Ficher    | Cat# BP154-1 |
| Glycine             | Sigma     | Cat# G-7126  |
| 100% Methanol       | Ficher    | Cat# A412-4  |
| HCl                 | Lab Stock | N/A          |