---
title: "Tris-Buffered Saline with Tween 20 (TBST)"
date: last-modified
date-format: full
author:
  - name: Pranav Mishra
    url: https://drpranavmishra.com
    orcid: 0000-0001-5219-6269 
    affiliation: Rush University
    affiliation-url: https://rushu.rush.edu 
citation: true
google-scholar: true
---

## Overview

<!-- Description of chemical here -->

### Uses

Tween-20 is a non-ionic detergent which acts as a temporary blocking agent to prevent non-specific protein-protein binding. In western blots, after the primary antibody has been allowed to bind appropriately, we need to prepare for the secondary antibody. First, we must wash the membrane to remove all excess primary antibody. By washing the membrane with a detergent, we prevent the primary antibody from inadventantly, incorrectly binding to an incorrect site (non-specific binding to the membrane). The antibody will have a preferential binding to the detergent.

Detergents are helpful temporary blockers - they can be washed away easily with aqeuous solutions.

## Components

* *10x Stock TBS*
* *Tween 20*
* $diH\_2O$

## Protocol

1. Add 800 mL of $diH\_2O$ to orange top container
2. Add 1 mL of *Tween 20* using a wide tip pipette (Tween 20 is very viscous)
3. Add \~199 mL of $diH\_2O$ down the side of the container until the total volume reaches 1 L

## Notes

Do not start with a 1x TBS that we may keep at the bench. This will have 20% Methanol added, which we do not want for TBST.

## References

1. Western blot buffers and stock solutions. Abcam. https://www.abcam.com/protocols/buffer-and-stock-solutions-for-western-blot

***

## Supplemental

### Key resources table

| REAGENT or RESOURCE | SOURCE     | IDENTIFIER    |
|---------------------|------------|---------------|
| **Chemicals**       |            |               |
| Tween 20            | Santa Cruz | Cat# SC-29113 |