name: Render and Publish

# on:
#   push:
#       branches:
#         - main

# you need these permissions to publish to GitHub pages
permissions: 
  contents: write
  pages: write
  
jobs:
    render-and-deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
          
        - name: Set up Quarto
          uses: quarto-dev/quarto-actions/setup@v2
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            # To install LaTeX to build PDF book 
            tinytex: true 